apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/instance: testehugo
    app.kubernetes.io/name: testehugo
  name: testehugo
  namespace: testehugo-helm
spec:
  maxReplicas: 10
  metrics:
  - pods:
      metricName: http_server_requests_seconds_sum_rate1m
      targetAverageValue: "45"
    type: Pods
  minReplicas: 2 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: testehugo
